Repository poetapp/explorer-web, pull requests merged in 2018-06, with the labels that each got.

#63 Security Headers
  _headers
  webpack.config.js
Labels: quality, security

#67 adds unit testing tools
  .travis.yml
  package-lock.json
  package.json
  src/canary.test.ts
  tests/unit/index.ts
  tsconfig.json
  typings/riteway/index.ts
  webpack.config.js
Labels: quality, testing

#70 Button/ Input/ Form Components
  package-lock.json
  package.json
  src/canary.test.ts
  src/components/atoms/Button/Button.scss
  src/components/atoms/Button/Button.stories.tsx
  src/components/atoms/Button/Button.test.tsx
  src/components/atoms/Button/Button.tsx
  src/components/atoms/Input/Input.scss
  src/components/atoms/Input/Input.stories.tsx
  src/components/atoms/Input/Input.test.tsx
  src/components/atoms/Input/Input.tsx
  src/components/molecules/Form/Form.scss
  src/components/molecules/Form/Form.stories.tsx
  src/components/molecules/Form/Form.test.tsx
  src/components/molecules/Form/Form.tsx
  src/components/styles/Colors.scss
  src/components/styles/Fonts.scss
  src/images/Images.tsx
  src/images/facebook.svg
  src/images/google.svg
  src/images/twitter2.svg
  tests/unit/index.ts
  tsconfig.json
  typings/riteway/index.d.ts
  webpack.config.js
Labels: ux
