Repository poetapp/explorer-web, pull requests merged in 2018-05, with the labels that each got.

#28 fixes lint errors
  .travis.yml
  package.json
  src/actions/index.ts
  src/actions/requests.ts
  src/bootstrap.ts
  src/components/ClassNameProps.ts
  src/components/PageLoader.tsx
  src/components/ResourceProvider.tsx
  src/components/Root.tsx
  src/components/atoms/Claim.tsx
  src/components/atoms/CopyableText.tsx
  src/components/atoms/DatePickerInput.tsx
  src/components/atoms/Hash.tsx
  src/components/atoms/SearchInput.tsx
  src/components/atoms/Work.tsx
  src/components/atoms/base/PoetApiResource.ts
  src/components/molecules/LatestWorks.tsx
  src/components/molecules/Pagination.tsx
  src/components/organisms/Footer.tsx
  src/components/organisms/Navbar.tsx
  src/components/organisms/WorksByProfile.tsx
  src/configuration.ts
  src/enums/FetchStatus.ts
  src/extensions/Array.ts
  src/extensions/Map.ts
  src/extensions/String.ts
  src/extensions/Window.ts
  src/helpers/PoetApi.ts
  src/helpers/UrlObject.ts
  src/images/Images.tsx
  src/index.tsx
  src/pages/Landing/LandingLoggedIn.tsx
  src/pages/Landing/Layout.tsx
  src/pages/Landing/Loader.tsx
  src/pages/Work/Layout.tsx
  src/pages/Work/Loader.tsx
  src/pages/Work/Overview.tsx
  src/pages/Work/Tabs/ContentTab.tsx
  src/pages/Work/Tabs/TechnicalTab.tsx
  src/pages/Work/WorkTabs.tsx
  src/pages/Works/Filters.tsx
  src/pages/Works/Layout.tsx
  src/pages/Works/Loader.tsx
  src/pages/Works/Works.tsx
  src/pages/index.ts
  src/reducers/FetchReducer.ts
  src/reducers/index.ts
  src/sagas/CacheInvalidationSaga.ts
  src/sagas/FetchSaga.ts
  src/sagas/NavbarSaga.ts
  src/sagas/index.ts
  src/selectors/fetch.ts
  src/store.ts
  src/store/PoetAppState.ts
  src/typings/require.ts
  tslint.json
Labels: in progress

#29 Adds package @po.et/stylelint-rules
  .stylelintrc
  .travis.yml
  package-lock.json
  package.json
  src/components/Root.scss
  src/components/atoms/DatePickerInput.scss
  src/components/atoms/Hash.scss
  src/components/molecules/LatestWorks.scss
  src/components/organisms/Footer.scss
  src/components/organisms/Navbar.scss
  src/components/organisms/WorksByProfile.scss
  src/components/styles/Animations.scss
  src/components/styles/Autocomplete.scss
  src/components/styles/Buttons.scss
  src/components/styles/Colors.scss
  src/components/styles/Fonts.scss
  src/components/styles/Forms.scss
  src/components/styles/Iframe.scss
  src/components/styles/OptionGroups.scss
  src/components/styles/Pagination.scss
  src/components/styles/Tabs.scss
  src/pages/Landing/LandingLoggedIn.scss
  src/pages/Landing/Layout.scss
  src/pages/Work/Layout.scss
  src/pages/Work/Overview.scss
  src/pages/Work/Tabs/ContentTab.scss
  src/pages/Work/Tabs/Tab.scss
  src/pages/Work/Tabs/TechnicalTab.scss
  src/pages/Works/Filters.scss
  src/pages/Works/Layout.scss
  src/pages/Works/Layout.tsx
  src/pages/Works/Works.scss
Labels: in progress, quality

#32 @po.et/tslint-rules@1.2.0
  package-lock.json
  package.json
  src/components/PageLoader.tsx
  src/components/ResourceProvider.tsx
  src/components/atoms/Claim.tsx
  src/components/atoms/CopyableText.tsx
  src/components/atoms/DatePickerInput.tsx
  src/components/atoms/Hash.tsx
  src/components/atoms/Work.tsx
  src/components/atoms/base/PoetApiResource.ts
  src/components/molecules/LatestWorks.tsx
  src/components/molecules/Pagination.tsx
  src/components/organisms/Navbar.tsx
  src/components/organisms/WorksByProfile.tsx
  src/enums/FetchStatus.ts
  src/extensions/Array.ts
  src/extensions/Map.ts
  src/extensions/String.ts
  src/helpers/PoetApi.ts
  src/index.tsx
  src/pages/Landing/LandingLoggedIn.tsx
  src/pages/Work/Layout.tsx
  src/pages/Work/Overview.tsx
  src/pages/Work/Tabs/ContentTab.tsx
  src/pages/Work/Tabs/TechnicalTab.tsx
  src/pages/Works/Filters.tsx
  src/pages/Works/Layout.tsx
  src/pages/Works/Loader.tsx
  src/pages/Works/Works.tsx
  src/reducers/FetchReducer.ts
  src/reducers/index.ts
  src/sagas/FetchSaga.ts
  src/sagas/NavbarSaga.ts
  src/selectors/fetch.ts
  src/store.ts
Labels: quality
