Repository poetapp/explorer-web, pull requests merged in 2018-07, with the labels that each got.

#100 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: don't merge

#114 adds circular dependency checker plugin
  package-lock.json
  package.json
  webpack.config.js
Labels: in progress, quality

#119 removes react packages from greenkeeper ignore
  package.json
Labels: quality

#98 Adds Log in for frost-api accounts
  README.md
  _redirects
  devServer.js
  env/development.json
  env/production.json
  package-lock.json
  package.json
  src/actions/index.ts
  src/components/Root.tsx
  src/components/atoms/Button/Button.stories.tsx
  src/components/atoms/Button/Button.tsx
  src/components/atoms/Input/Input.scss
  src/components/atoms/Input/Input.tsx
  src/components/atoms/LoadingPage/LoadingPage.scss
  src/components/atoms/LoadingPage/LoadingPage.tsx
  src/components/containers/LoadingPage.container.tsx
  src/components/containers/Login.container.tsx
  src/components/molecules/Form/Form.scss
  src/components/molecules/Form/Form.stories.tsx
  src/components/molecules/Form/Form.test.tsx
  src/components/molecules/Form/Form.tsx
  src/components/molecules/Forms/SignIn/SignIn.scss
  src/components/molecules/Forms/SignIn/SignIn.stories.tsx
  src/components/molecules/Forms/SignIn/SignIn.tsx
  src/components/molecules/Login/Login.tsx
  src/config/features.ts
  src/configuration.ts
  src/helpers/helpers.ts
  src/index.tsx
  src/interfaces/Props.ts
  src/pages/Login/Login.layout.tsx
  src/pages/Login/Login.loader.tsx
  src/pages/index.ts
  src/reducers/LoadingPage.test.ts
  src/reducers/LoadingPage.ts
  src/reducers/Profile.test.ts
  src/reducers/Profile.ts
  src/reducers/SignIn.test.ts
  src/reducers/SignIn.ts
  src/reducers/User.test.ts
  src/reducers/User.ts
  src/reducers/index.ts
  src/sagas/GetProfile.test.ts
  src/sagas/GetProfile.ts
  src/sagas/SignIn.test.ts
  src/sagas/SignIn.ts
  src/sagas/index.ts
  src/singletons/FrostClient.ts
  src/store.ts
  src/typings/react-feature-toggles/index.d.ts
  tests/unit/index.ts
  tsconfig.json
  webpack.config.js
Labels: don't merge
